apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: sjl-io-tls
spec:
  secretName: sjl-io
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: sjl.io
  dnsNames:
    - sjl.io
    - www.sjl.io
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - sjl.io
          - www.sjl.io
