apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim # is not yet a storage until attch to a pod 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
